export default {// 定义actiontype 在指定的js中导出
    // 修改 modal 是否课件
    ONCLOSE_MODAL:'ONCLOSE_MODAL',// 名字可以自己定义
    ONOPEN_MODAL:'ONOPEN_MODAL',
    // Filelist
    CHANGE_FILELIST:'CHANGE_FILELIST',
    CHANGE_UPLOADED:'CHANGE_UPLOADED',
    // preAndtable
    CHANGE_TABLE:'CHANGE_TABLE',
    CHANGE_ISDOWNLOADABLE:'CHANGE_ISDOWNLOADABLE',
    CHANGE_DOWNLOADING:'CHANGE_DOWNLOADING',
    CHANHE_ISLOADING:'CHANHE_ISLOADING',
    CHANGE_ISPREDICTING:'CHANGE_ISPREDICTING',
    CHANGE_PLOT_DATA:'CHANGE_PLOT_DATA',
    CHANGE_COUNTER:'CHANGE_COUNTER',
}