/**
 * 僵尸企业特征 词云
 * 
 */

import React, {useEffect} from 'react';
import { WordCloud } from '@antv/g2plot';

function WordCloudZombie(){
    useEffect(()=>{
        const data = [
            {
                word:'行业',
                weight:'100',
                id:'1',
                color:''
            },
            {
                word:'区域',
                weight:'90',
                id:'2',
                color:''
            },
            {
                word:'企业类型',
                weight:'50',
                id:'3',
                color:''
            },
            {
                word:'控制人类型',
                weight:'60',
                id:'4',
                color:''
            },
            {
                word:'控制人持股比例',
                weight:'20',
                id:'5',
                color:''
            },
            {
                word:'注册资本',
                weight:'20',
                id:'6',
                color:''
            },
            {
                word:'专利',
                weight:'20',
                id:'7',
                color:''
            },
            {
                word:'商标',
                weight:'20',
                id:'8',
                color:''
            },
            {
                word:'著作权',
                weight:'20',
                id:'9',
                color:''
            },
            {
                word:'债权融资额度',
                weight:'20',
                id:'10',
                color:''
            },
            {
                word:'债权融资成本',
                weight:'20',
                id:'11',
                color:''
            },
            {
                word:'债权融资额度',
                weight:'20',
                id:'12',
                color:''
            },
            {
                word:'股权融资额度',
                weight:'20',
                id:'13',
                color:''
            },
            {
                word:'股权融资成本',
                weight:'20',
                id:'14',
                color:''
            },
            {
                word:'内部融资和贸易融资额度',
                weight:'20',
                id:'15',
                color:''
            },
            {
                word:'内部融资和贸易融资成本',
                weight:'20',
                id:'16',
                color:''
            },
            {
                word:'项目融资和政策融资成本',
                weight:'20',
                id:'17',
                color:''
            },
            {
                word:'资产总额',
                weight:'20',
                id:'18',
                color:''
            },
            {
                word:'负债总额',
                weight:'20',
                id:'19',
                color:''
            },
            {
                word:'营业总收入',
                weight:'20',
                id:'20',
                color:''
            },
            {
                word:'主营业务收入',
                weight:'20',
                id:'21',
                color:''
            },
            {
                word:'利润总额',
                weight:'20',
                id:'22',
                color:''
            },
            {
                word:'净利润',
                weight:'20',
                id:'23',
                color:''
            },
            {
                word:'纳税总额',
                weight:'20',
                id:'24',
                color:''
            },
            {
                word:'所有者权益合计',
                weight:'20',
                id:'25',
                color:''
            },
        ];

        const wordCloud = new WordCloud(document.getElementById('WordCloudZombie'), {
            data,
            wordStyle:{
                fontSize:[10,15]
            },
            width:300,
            height:300,
            shape:'circle'
        });
        wordCloud.render();
    })

    return(
        <div id='WordCloudZombie'></div>
    )
}

export default WordCloudZombie;